version: '3.7'

services:
  backend:
    container_name: backend
    build: 
      context: ./node
      dockerfile: ./dockerfile-node
    ports:
      - "3032:3032"

  frontend: 
    build: 
      context: .
      dockerfile: ./dockerfile-react
    ports:
      - 3000:3000
    volumes:
      - './:/app'
      - '/app/node_modules'
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
      